### ISSUE TITLE
Add support to custom filter

### ISSUE THREAD

**Issue by pragmaticivan** [mustafaturan/authable#24]
Would you consider adding extra filters for the resource owner?

ex:
```elixir
Authable.GrantType.Password.authorize(%{
        "email" => "foo@example.com",
        "password" => "12345678",
        "client_id" => "52024ca6-cf1d-4a9d-bfb6-9bc5023ad56e",
        "scope" => "read"
        "filter" => %{"tenant_id": "1", "state": "active"}
 %})
```

```elixir
def authorize(%{"email" => email, "password" => password, "client_id" => client_id, "scope" => scopes, "filter": filter}) do
    client = @repo.get(@client, client_id)
    filter_group = Map.merge(%{email: email}, filter)
    user = @repo.get_by(@resource_owner, filter_group)
    create_tokens(client, user, password, scopes)
end
```

I need to use that with a state system where I can disable/enable users or have users with the same email but in different tentants (apps).

**Comment by creeonix** [comment]
I think that you should do a check before you get to `authorize` method in the first place because logic for user check is not always limited to DB checks, you may want to decide if you want to allow user to log-in based on `user.settings` or `user.priv_settings`

So, I'd say this logic does not belong to the package at all.

**Comment by mustafaturan** [comment]
@pragmaticivan 

There is not an intention for the `authable`. You can implement your custom authorization. Also, you can check the `canary` lib.
